#ifndef SHMFIFO_ERROR_H_
#define SHMFIFO_ERROR_H_
#ifdef __cplusplus
extern "C" {
#endif
enum {
  SHMFIFO_ERR_NO = 0,
  SHMFIFO_ERR_OPEN,
  SHMFIFO_ERR_LOAD_VERSION_PREAD,
  SHMFIFO_ERR_LOAD_VERSION_SIZE,
  SHMFIFO_ERR_OBJ_POOL_INIT_ENQUEUE,
  SHMFIFO_ERR_FULL,
  SHMFIFO_ERR_EMPTY,
  SHMFIFO_ERR_PUSH_OBJ_ALLOC,
  SHMFIFO_ERR_PUSH_OBJ_ENQUEUE,
  SHMFIFO_ERR_POP_OBJ_DEQUEUE,
  SHMFIFO_ERR_POP_BUF_SIZE,
  SHMFIFO_ERR_POP_OBJ_FREE,
  SHMFIFO_ERR_POP_DATA_OBJ_DEQUEUE,
  SHMFIFO_ERR_POP_DATA_BUF_SIZE,
  SHMFIFO_ERR_POP_DATA_OBJ_FREE,
  SHMFIFO_ERR_MAGIC_VERSION,
  SHMFIFO_ERR_FILE_READY_FSTAT,
  SHMFIFO_ERR_FILE_SIZE,
  SHMFIFO_ERR_FORMAT_FTRUNCATE,
  SHMFIFO_ERR_FORMAT_FTRUNCATE_SIZE,
  SHMFIFO_ERR_MAX
};
#ifdef __cplusplus
}
#endif
#endif
